### ISSUE TITLE
Clean the stack traces for Botsing

### ISSUE THREAD

**Issue by pderakhshanfar** [STAMP-project/botsing#9] opened 2018-10-03 13:53 UTC
#### Description
These processes should be done in the stack trace for cleaning it:
- [x] converting the chained stack traces to the single ones
~~Removing frames which point to the annotations.~~
- [x] Removing the error message

* The cleaning process should be defined the [botsing-preprocessing](https://github.com/STAMP-project/botsing/tree/master/botsing-preprocessing) sub-module.

**Comment by spookyvale** [comment] 2018-10-12 08:54
A question on the second item...
Does one of the logs in Evocrash-demo contain a frame pointing to an annotation? It would help me test my code. Thanks

**Comment by pderakhshanfar** [comment] 2018-10-15 09:52
Dear @spookyvale 

I do not think that we have a sample of that in the demo. But, I can give  you an example:

In case [XWIKI-13303](https://jira.xwiki.org/browse/XWIKI-13303), we have a chained stack trace. In the second part of it, which is mentioned below, the 5th frame (`org.xwiki.display.internal.DefaultDocumentDisplayer.display(DefaultDocumentDisplayer.java:96)`) points to the annotation.

```
java.lang.NullPointerException
	at com.xpn.xwiki.doc.XWikiDocument.getXDOM(XWikiDocument.java:8451)
	at org.xwiki.display.internal.DocumentContentDisplayer.getContent(DocumentContentDisplayer.java:280)
	at org.xwiki.display.internal.DocumentContentDisplayer.display(DocumentContentDisplayer.java:248)
	at org.xwiki.display.internal.DocumentContentDisplayer.display(DocumentContentDisplayer.java:131)
	at org.xwiki.display.internal.DocumentContentDisplayer.display(DocumentContentDisplayer.java:58)
	at org.xwiki.display.internal.DefaultDocumentDisplayer.display(DefaultDocumentDisplayer.java:96)
	at org.xwiki.display.internal.DefaultDocumentDisplayer.display(DefaultDocumentDisplayer.java:39)
	at org.xwiki.sheet.internal.SheetDocumentDisplayer.display(SheetDocumentDisplayer.java:123)
	at org.xwiki.sheet.internal.SheetDocumentDisplayer.display(SheetDocumentDisplayer.java:52)
	at org.xwiki.display.internal.ConfiguredDocumentDisplayer.display(ConfiguredDocumentDisplayer.java:68)
	at org.xwiki.display.internal.ConfiguredDocumentDisplayer.display(ConfiguredDocumentDisplayer.java:42)
	at com.xpn.xwiki.doc.XWikiDocument.getRenderedContent(XWikiDocument.java:1171)
	at com.xpn.xwiki.doc.XWikiDocument.getRenderedContent(XWikiDocument.java:1134)
	at com.xpn.xwiki.doc.XWikiDocument.getRenderedContent(XWikiDocument.java:1186)
	at com.xpn.xwiki.api.Document.getRenderedContent(Document.java:717)
	at sun.reflect.GeneratedMethodAccessor473.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
```

You can download the right version of the source code from [here](https://github.com/xwiki/xwiki-platform/releases/tag/xwiki-platform-8.0). The target class is placed in this directory: `xwiki-platform-core/xwiki-platform-display/xwiki-platform-display-api/src/main/java/org/xwiki/display/internal/DocumentContentDisplayer.java`

**Comment by spookyvale** [comment] 2018-10-18 13:43
can I assume to have access to the source code? Going through the byte-code is feasible, not very performing though...

**Comment by pderakhshanfar** [comment] 2018-10-19 09:30
@spookyvale We cannot have access to the source code in Botsing. I understand your problem in detecting annotations at the byte-code level. If it is not possible, you can skip it for now.

 The primary goal of this pre-processing is finding the frames that Botsing cannot use them as the target frame. For instance, annotations. I will take a look at the source code of EvoSuite and try to find a way to detect it using this dependency. If I find something about it, I will update you.

**Comment by spookyvale** [comment] 2018-12-17 14:20
@pasquy73 will continue my work on this issue

**Comment by pasquy73** [comment] 2019-01-14 11:17
We are exploring the use cases that can raise exceptions by using annotations. The only significant use case concerns the possibility to use the annotations to mark objects on which perform some operations that can lead exceptions. In this case the annotation does not raise the exception by itself, but somehow plays a role. I don't think that in this case the lines should be erased: do you agree? Can you identify other, more specific, use cases in which annotations can directly lead exceptions?

**Comment by xdevroey** [comment] 2019-03-01 12:38
Hi @pasquy73, I removed that one from the list. Detecting lines pointing to annotations requires to parse and analyze the source code of the application for the given stack trace. This is too complex. 

For the nested exceptions, we should get the deepest one that has one of the classes of the projects amongst its frames. For the example that you sent : 
```
javax.servlet.ServletException: Something bad happened
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:60)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.ExceptionHandlerFilter.doFilter(ExceptionHandlerFilter.java:28)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.example.myproject.OutputBufferFilter.doFilter(OutputBufferFilter.java:33)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: com.example.myproject.MyProjectServletException
    at com.example.myproject.MyServlet.doPost(MyServlet.java:169)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.example.myproject.OpenSessionInViewFilter.doFilter(OpenSessionInViewFilter.java:30)
    ... 27 more
Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [com.example.myproject.MyEntity]
    at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
    at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
    at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:64)
    at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2329)
    at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2822)
    at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:71)
    at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:268)
    at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:321)
    at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:204)
    at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:130)
    at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:210)
    at org.hibernate.event.def.DefaultSaveEventListener.saveWithGeneratedOrRequestedId(DefaultSaveEventListener.java:56)
    at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:195)
    at org.hibernate.event.def.DefaultSaveEventListener.performSaveOrUpdate(DefaultSaveEventListener.java:50)
    at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:93)
    at org.hibernate.impl.SessionImpl.fireSave(SessionImpl.java:705)
    at org.hibernate.impl.SessionImpl.save(SessionImpl.java:693)
    at org.hibernate.impl.SessionImpl.save(SessionImpl.java:689)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:344)
    at $Proxy19.save(Unknown Source)
    at com.example.myproject.MyEntityService.save(MyEntityService.java:59)
    at com.example.myproject.MyServlet.doPost(MyServlet.java:164)
    ... 32 more
Caused by: java.sql.SQLException: Violation of unique constraint MY_ENTITY_UK_1: duplicate value(s) for column(s) MY_COLUMN in statement [...]
    at org.hsqldb.jdbc.Util.throwError(Unknown Source)
    at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
    at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:57)
    ... 54 more
```

We keep only the second exception (starting from the deepest level) because it has frames pointing to the software under test:

```
org.hibernate.exception.ConstraintViolationException: could not insert: [com.example.myproject.MyEntity]
    at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
    at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
    at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:64)
    at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2329)
    at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2822)
    at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:71)
    at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:268)
    at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:321)
    at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:204)
    at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:130)
    at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:210)
    at org.hibernate.event.def.DefaultSaveEventListener.saveWithGeneratedOrRequestedId(DefaultSaveEventListener.java:56)
    at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:195)
    at org.hibernate.event.def.DefaultSaveEventListener.performSaveOrUpdate(DefaultSaveEventListener.java:50)
    at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:93)
    at org.hibernate.impl.SessionImpl.fireSave(SessionImpl.java:705)
    at org.hibernate.impl.SessionImpl.save(SessionImpl.java:693)
    at org.hibernate.impl.SessionImpl.save(SessionImpl.java:689)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:344)
    at $Proxy19.save(Unknown Source)
    at com.example.myproject.MyEntityService.save(MyEntityService.java:59)
    at com.example.myproject.MyServlet.doPost(MyServlet.java:164)
```

For the rest, I think @spookyvale already implemented most of the methods to clean the frames themselves. 

More information about chained exception [here](https://www.baeldung.com/java-chained-exceptions) and in the [official Java documentation](https://docs.oracle.com/javase/tutorial/essential/exceptions/chained.html).

**Comment by pasquy73** [comment] 2019-03-09 11:19
Just a consideration about nested exceptions, I undestood that I've to consider the deepest "caused by" which refers to frames pointing of the software under test. 
But my question is:
how can I get the level of the exception?
Would I use another parameter (i.e. path = com.example.myproject) to get the right exception level?

**Comment by pasquy73** [comment] 2019-03-12 10:39
Otherwise we can add another parameter (i.e. level = 2) to stop "the flatten task" to the second exception level.

**Comment by xdevroey** [comment] 2019-03-12 10:51
I am not sure to understand your question. We do not know which `caused by` is the one that has to be selected beforehand. 

The idea is to start from the deepest stack trace (the deepest `caused b`) and see if there is a frame there that points to the source code of the application. If there is such a frame, then we consider that deepest exception as the one we try to reproduce. If not, then we repeat the check with the enclosing one. 

In the example above, we do not select the deepest `caused by` because no frame is pointing to the application. Instead, we take the one that is just before because the frame `at com.example.myproject.MyEntityService.save(MyEntityService.java:59)` points to a class (`com.example.myproject.MyEntityService`) of the project. 

Hope it clarifies things.

**Comment by pasquy73** [comment] 2019-03-13 13:54
Actually the botsing-preprocessing uses 3 parameters: 
1. input file (-i=crash_log.txt), 
2. output file (-o=output_log.log) and 
3. flatten option (-f).

Example: `java -jar botsing-preprocessing.jar -f -i=crash_log.txt -o=output_log.log` 

When you said: 

> there is a frame there that points to the source code of the application

I think that I have to use another parameter (path or level or source_file); i.e. `path=com.example.myproject` or `level=2` or `source_file=path_of_source.zip` to understand what **caused by** must be used.
I hope it's clear now.

**Comment by xdevroey** [comment] 2019-03-13 14:41
Ha ok, I see, you indeed need to know what the packages of the application are. I suggest to proceed as with ExRunner (a tool we use for our evaluation) and have a parameter `package=com.example.*` with a regular expression pointing to the classes of the project. 

So during the filtering, if a frame matches the regular expression of the `package` parameter, it means that the frame belongs to the project.

**Comment by pasquy73** [comment] 2019-03-14 15:05
I completed the "chained stack traces" task, and I committed in [github](https://github.com/pasquy73/botsing/tree/stacktrace-processing)

**Comment by xdevroey** [comment] 2019-03-14 15:07
Great @pasquy73! Could you do a pull request to the STAMP repository?

**Comment by pasquy73** [comment] 2019-03-14 15:09
Done

**Comment by xdevroey** [comment] 2019-03-14 15:12
I think you did the pull request to @spookyvale/botsing repo. Could you do it for the STAMP one?

**Comment by xdevroey** [comment] 2019-03-22 09:28
See release [botsing-1.0.4](https://github.com/STAMP-project/botsing/releases/tag/botsing-1.0.4)

**Closed by xdevroey** 2019-03-22 09:28 UTC
Labels: botsing, enhancement
