### ISSUE TITLE
test_dir option has no effect on the Maven plugin

### ISSUE THREAD

**Issue by gibello** [STAMP-project/botsing#66] opened 2019-03-22 09:51 UTC
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [minor]
- **Tool/Service/Component**: [Botsing maven plugin (probably CLI as well)]
- **Execution Environment**: [Ubuntu Linux 18.04]
- **Reporter**: [Pierre-Yves Gibello, pyg@ow2.org]

#### Description

Adding -Dtest_dir=/tmp/botsing-tests to maven botsing invocation has no effect (test generated locally in crash-reproduction-test/ ).

The code looks fuzzy concerning that:
- Class eu.stamp.botsing.model.generation.CommandLineParameters has only a "out_dir" option (but no "test_dir").
- Maven plugin mojo has a parameter called "test_dir", but never used in the code (and with wrong default value, "crashreproduction-tests" as the doc specifies "crash-reproduction-tests").

So, I don't know exactly what option to use... but it is probably not possible to specify an output test dir at all (with maven, at least, I'm sure of that).

#### Steps to reproduce

Add -Dtest_dir=any-directory to maven command line.

Example:
mvn eu.stamp-project:botsing-maven:1.0.4-SNAPSHOT:botsing -Dcrash_log=/tmp/ex1.log -Dtarget_frame=1 -Dtest_dir=/tmp/botsing-tests

**Comment by xdevroey** [comment] 2019-03-22 10:02
Hi @gibello, I am not sure to see what you are referring to. The Maven plugin can, for now, only be used to reproduce stack traces. Models have to be generated using the command line, as explained in the [tutorial](https://github.com/STAMP-project/evosuite-model-seeding-tutorial). Are you trying to use it to generate models? 

If not, the class `eu.stamp.botsing.model.generation.CommandLineParameters` is not the right one to look at. We use `-Dtest_dir=` in our integration tests and it works fine:
https://github.com/STAMP-project/botsing/blob/c4a17693885cd55089fa1cfb4afdac9e2f3f4be2/botsing-reproduction/src/test/java/eu/stamp/botsing/BotsingTest.java#L72

**Comment by gibello** [comment] 2019-03-25 08:50
I'm just trying to generate outputs somewhere else that in crash-reproduction-test/ dir (eg. somewhere in /tmp).

**Comment by xdevroey** [comment] 2019-03-25 09:03
Ok, seems to be an issue in the Maven plugin then. @luandrea could you double check?

**Comment by luandrea** [comment] 2019-03-25 15:27
Hi Xavier,
Maven plugin doesn't handle this parameter, I will add it now.

I see that some parameters are passed as:
`-PARAMETER_NAME PARAMETER_VALUE`

And someone else like this:
`-DPARAMETER_NAME=PARAMETER_VALUE`

Could you give me a list of parameter that I should take into account and the way to add them?

For now I'm adding these:

- -crashLog
- -targetFrame
- -projectCP
- -Dpopulation
- -Dsearch_budget
- -Dglobal_timeout
- -Dtest_dir
- -Drandom_seed

**Comment by xdevroey** [comment] 2019-03-25 15:41
Hi Luca, the list is available in #30

**Comment by luandrea** [comment] 2019-03-25 16:12
Ok, great. I just created the pull request to handle them.

**Comment by xdevroey** [comment] 2019-03-27 09:22
Should be fixed by #68

**Closed by xdevroey** 2019-03-27 09:22 UTC
Labels: bug, maven-plugin
